name: Upload Release to UpgradeLink

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upgradeLink-upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to UpgradeLink
        uses: toolsetlink/upgradelink-action@3.0.2
        with:
          access_key: ${{ secrets.UPGRADE_LINK_ACCESS_KEY }}
          access_secret: ${{ secrets.UPGRADE_LINK_ACCESS_SECRET }}
          config: |
            {
              "app_type": "tauri",
              "request": {
                "app_key": "${{ secrets.UPGRADE_LINK_APP_KEY }}",
                "latest_json_url": "https://github.com/ayangweb/BongoCat/releases/latest/download/latest.json"
              }
            }
